id: Okta-xsiam-logs
version: -1
name: Okta-xsiam-logs
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: a4448d1e-6068-4869-8925-758702af4fbe
    type: start
    task:
      id: a4448d1e-6068-4869-8925-758702af4fbe
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: 1ed1c365-9333-4a42-8e4b-2908ced62746
    type: regular
    task:
      id: 1ed1c365-9333-4a42-8e4b-2908ced62746
      version: -1
      name: DeleteContext
      description: |-
        Delete field from context.

        This automation runs using the default Limited User role, unless you explicitly change the permissions.
        For more information, see the section about permissions here:
        https://docs.paloaltonetworks.com/cortex/cortex-xsoar/6-2/cortex-xsoar-admin/playbooks/automations.html
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 230
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: 2792b11b-8c35-49b5-84c1-6122b640bfa5
    type: regular
    task:
      id: 2792b11b-8c35-49b5-84c1-6122b640bfa5
      version: -1
      name: okta-fetch-logs
      description: Brings logs from okta.
      script: Okta SIEM|||okta-fetch-logs
      type: regular
      iscommand: true
      brand: Okta SIEM
    nexttasks:
      '#none#':
      - "3"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 410
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: a0f8874f-a740-4a8f-8a33-af82938da135
    type: regular
    task:
      id: a0f8874f-a740-4a8f-8a33-af82938da135
      version: -1
      name: closeInvestigation
      description: Close the current incident
      script: Builtin|||closeInvestigation
      type: regular
      iscommand: true
      brand: Builtin
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 590
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 635,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
fromversion: 5.0.0
description: Runs Okta logs pack with fetch logs commands

